title = "Matt Pudig"
baseURL = "https://mpudig.github.io/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Matt Pudig"
  description = "My personal website"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "16pt"
    pageWidth = "1150px"
    avatarSize = "210px"
    colorBlack = "#222222"
    colorRed = "#64a6f9"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files