baseURL = 'https://mpudig.github.io/'
languageCode = 'en-us'
title = 'matt pudig'
theme = 'researcher'

[params]
  author = "Matt Pudig"
  description = "my personal website"
  favicon = "favicon.ico"
  customCSS = ["css/custom.css"]

